//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SearchGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class SearchGrammarParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		NEWLINE=10, WORD=11, STRING=12, WS=13;
	public const int
		RULE_value = 0, RULE_keylist = 1, RULE_kvsearch = 2, RULE_args = 3, RULE_function = 4, 
		RULE_term = 5, RULE_negation = 6, RULE_or = 7, RULE_and = 8, RULE_query = 9;
	public static readonly string[] ruleNames = {
		"value", "keylist", "kvsearch", "args", "function", "term", "negation", 
		"or", "and", "query"
	};

	private static readonly string[] _LiteralNames = {
		null, "'{'", "','", "'}'", "'-'", "':'", "'('", "')'", "'!'", "'|'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "NEWLINE", 
		"WORD", "STRING", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SearchGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SearchGrammarParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SearchGrammarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SearchGrammarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class ValueContext : ParserRuleContext {
		public ITerminalNode WORD() { return GetToken(SearchGrammarParser.WORD, 0); }
		public ITerminalNode STRING() { return GetToken(SearchGrammarParser.STRING, 0); }
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISearchGrammarVisitor<TResult> typedVisitor = visitor as ISearchGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 0, RULE_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 20;
			_la = TokenStream.LA(1);
			if ( !(_la==WORD || _la==STRING) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class KeylistContext : ParserRuleContext {
		public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public ITerminalNode[] WS() { return GetTokens(SearchGrammarParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(SearchGrammarParser.WS, i);
		}
		public KeylistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_keylist; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.EnterKeylist(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.ExitKeylist(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISearchGrammarVisitor<TResult> typedVisitor = visitor as ISearchGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitKeylist(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public KeylistContext keylist() {
		KeylistContext _localctx = new KeylistContext(Context, State);
		EnterRule(_localctx, 2, RULE_keylist);
		int _la;
		try {
			int _alt;
			State = 58;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case WORD:
			case STRING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 22; value();
				}
				break;
			case T__0:
				EnterOuterAlt(_localctx, 2);
				{
				State = 23; Match(T__0);
				State = 27;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==WS) {
					{
					{
					State = 24; Match(WS);
					}
					}
					State = 29;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 46;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 30; value();
						State = 34;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						while (_la==WS) {
							{
							{
							State = 31; Match(WS);
							}
							}
							State = 36;
							ErrorHandler.Sync(this);
							_la = TokenStream.LA(1);
						}
						State = 37; Match(T__1);
						State = 41;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						while (_la==WS) {
							{
							{
							State = 38; Match(WS);
							}
							}
							State = 43;
							ErrorHandler.Sync(this);
							_la = TokenStream.LA(1);
						}
						}
						} 
					}
					State = 48;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
				}
				State = 49; value();
				State = 53;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==WS) {
					{
					{
					State = 50; Match(WS);
					}
					}
					State = 55;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 56; Match(T__2);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class KvsearchContext : ParserRuleContext {
		public KeylistContext keylist() {
			return GetRuleContext<KeylistContext>(0);
		}
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public KvsearchContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_kvsearch; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.EnterKvsearch(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.ExitKvsearch(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISearchGrammarVisitor<TResult> typedVisitor = visitor as ISearchGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitKvsearch(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public KvsearchContext kvsearch() {
		KvsearchContext _localctx = new KvsearchContext(Context, State);
		EnterRule(_localctx, 4, RULE_kvsearch);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__3) {
				{
				State = 60; Match(T__3);
				}
			}

			State = 63; keylist();
			State = 64; Match(T__4);
			State = 65; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgsContext : ParserRuleContext {
		public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public ITerminalNode[] WS() { return GetTokens(SearchGrammarParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(SearchGrammarParser.WS, i);
		}
		public ArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_args; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.EnterArgs(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.ExitArgs(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISearchGrammarVisitor<TResult> typedVisitor = visitor as ISearchGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgsContext args() {
		ArgsContext _localctx = new ArgsContext(Context, State);
		EnterRule(_localctx, 6, RULE_args);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 67; value();
					State = 71;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==WS) {
						{
						{
						State = 68; Match(WS);
						}
						}
						State = 73;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					State = 74; Match(T__1);
					State = 78;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
					while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
						if ( _alt==1 ) {
							{
							{
							State = 75; Match(WS);
							}
							} 
						}
						State = 80;
						ErrorHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
					}
					}
					} 
				}
				State = 85;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			State = 87;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==WORD || _la==STRING) {
				{
				State = 86; value();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		public ITerminalNode WORD() { return GetToken(SearchGrammarParser.WORD, 0); }
		public ArgsContext args() {
			return GetRuleContext<ArgsContext>(0);
		}
		public ITerminalNode[] WS() { return GetTokens(SearchGrammarParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(SearchGrammarParser.WS, i);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISearchGrammarVisitor<TResult> typedVisitor = visitor as ISearchGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 8, RULE_function);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 89; Match(WORD);
			State = 90; Match(T__5);
			State = 94;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 91; Match(WS);
					}
					} 
				}
				State = 96;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			}
			State = 97; args();
			State = 101;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==WS) {
				{
				{
				State = 98; Match(WS);
				}
				}
				State = 103;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 104; Match(T__6);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		public KvsearchContext kvsearch() {
			return GetRuleContext<KvsearchContext>(0);
		}
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		public QueryContext query() {
			return GetRuleContext<QueryContext>(0);
		}
		public ITerminalNode[] WS() { return GetTokens(SearchGrammarParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(SearchGrammarParser.WS, i);
		}
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.EnterTerm(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.ExitTerm(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISearchGrammarVisitor<TResult> typedVisitor = visitor as ISearchGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TermContext term() {
		TermContext _localctx = new TermContext(Context, State);
		EnterRule(_localctx, 10, RULE_term);
		int _la;
		try {
			State = 125;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 106; kvsearch();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 107; value();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 108; function();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 109; Match(T__5);
				State = 113;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==WS) {
					{
					{
					State = 110; Match(WS);
					}
					}
					State = 115;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 116; query();
				State = 120;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==WS) {
					{
					{
					State = 117; Match(WS);
					}
					}
					State = 122;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 123; Match(T__6);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NegationContext : ParserRuleContext {
		public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public NegationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_negation; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.EnterNegation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.ExitNegation(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISearchGrammarVisitor<TResult> typedVisitor = visitor as ISearchGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNegation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NegationContext negation() {
		NegationContext _localctx = new NegationContext(Context, State);
		EnterRule(_localctx, 12, RULE_negation);
		try {
			State = 130;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
			case T__3:
			case T__5:
			case WORD:
			case STRING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 127; term();
				}
				break;
			case T__7:
				EnterOuterAlt(_localctx, 2);
				{
				State = 128; Match(T__7);
				State = 129; term();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrContext : ParserRuleContext {
		public NegationContext[] negation() {
			return GetRuleContexts<NegationContext>();
		}
		public NegationContext negation(int i) {
			return GetRuleContext<NegationContext>(i);
		}
		public ITerminalNode[] WS() { return GetTokens(SearchGrammarParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(SearchGrammarParser.WS, i);
		}
		public OrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_or; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.EnterOr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.ExitOr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISearchGrammarVisitor<TResult> typedVisitor = visitor as ISearchGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OrContext or() {
		OrContext _localctx = new OrContext(Context, State);
		EnterRule(_localctx, 14, RULE_or);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 148;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 132; negation();
					State = 136;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==WS) {
						{
						{
						State = 133; Match(WS);
						}
						}
						State = 138;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					State = 139; Match(T__8);
					State = 143;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==WS) {
						{
						{
						State = 140; Match(WS);
						}
						}
						State = 145;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
					} 
				}
				State = 150;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
			}
			State = 151; negation();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AndContext : ParserRuleContext {
		public OrContext[] or() {
			return GetRuleContexts<OrContext>();
		}
		public OrContext or(int i) {
			return GetRuleContext<OrContext>(i);
		}
		public ITerminalNode[] WS() { return GetTokens(SearchGrammarParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(SearchGrammarParser.WS, i);
		}
		public AndContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_and; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.EnterAnd(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.ExitAnd(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISearchGrammarVisitor<TResult> typedVisitor = visitor as ISearchGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAnd(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AndContext and() {
		AndContext _localctx = new AndContext(Context, State);
		EnterRule(_localctx, 16, RULE_and);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 158;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 153; or();
					State = 154; Match(WS);
					}
					} 
				}
				State = 160;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			}
			State = 161; or();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QueryContext : ParserRuleContext {
		public AndContext and() {
			return GetRuleContext<AndContext>(0);
		}
		public QueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.EnterQuery(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISearchGrammarListener typedListener = listener as ISearchGrammarListener;
			if (typedListener != null) typedListener.ExitQuery(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISearchGrammarVisitor<TResult> typedVisitor = visitor as ISearchGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQuery(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QueryContext query() {
		QueryContext _localctx = new QueryContext(Context, State);
		EnterRule(_localctx, 18, RULE_query);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 163; and();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\xF', '\xA8', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\a', '\x3', '\x1C', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '\x1F', '\v', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '#', '\n', '\x3', '\f', 
		'\x3', '\xE', '\x3', '&', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', 
		'\x3', '*', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '-', '\v', '\x3', 
		'\a', '\x3', '/', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '\x32', '\v', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '\x36', '\n', '\x3', '\f', 
		'\x3', '\xE', '\x3', '\x39', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x5', '\x3', '=', '\n', '\x3', '\x3', '\x4', '\x5', '\x4', '@', '\n', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\a', '\x5', 'H', '\n', '\x5', '\f', '\x5', '\xE', 
		'\x5', 'K', '\v', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', 'O', 
		'\n', '\x5', '\f', '\x5', '\xE', '\x5', 'R', '\v', '\x5', '\a', '\x5', 
		'T', '\n', '\x5', '\f', '\x5', '\xE', '\x5', 'W', '\v', '\x5', '\x3', 
		'\x5', '\x5', '\x5', 'Z', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\a', '\x6', '_', '\n', '\x6', '\f', '\x6', '\xE', '\x6', '\x62', 
		'\v', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', '\x66', '\n', '\x6', 
		'\f', '\x6', '\xE', '\x6', 'i', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\a', 
		'\a', 'r', '\n', '\a', '\f', '\a', '\xE', '\a', 'u', '\v', '\a', '\x3', 
		'\a', '\x3', '\a', '\a', '\a', 'y', '\n', '\a', '\f', '\a', '\xE', '\a', 
		'|', '\v', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', '\x80', '\n', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', '\x85', '\n', 
		'\b', '\x3', '\t', '\x3', '\t', '\a', '\t', '\x89', '\n', '\t', '\f', 
		'\t', '\xE', '\t', '\x8C', '\v', '\t', '\x3', '\t', '\x3', '\t', '\a', 
		'\t', '\x90', '\n', '\t', '\f', '\t', '\xE', '\t', '\x93', '\v', '\t', 
		'\a', '\t', '\x95', '\n', '\t', '\f', '\t', '\xE', '\t', '\x98', '\v', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\a', '\n', '\x9F', '\n', '\n', '\f', '\n', '\xE', '\n', '\xA2', '\v', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x2', '\x2', '\f', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', 
		'\x12', '\x14', '\x2', '\x3', '\x3', '\x2', '\r', '\xE', '\x2', '\xB4', 
		'\x2', '\x16', '\x3', '\x2', '\x2', '\x2', '\x4', '<', '\x3', '\x2', '\x2', 
		'\x2', '\x6', '?', '\x3', '\x2', '\x2', '\x2', '\b', 'U', '\x3', '\x2', 
		'\x2', '\x2', '\n', '[', '\x3', '\x2', '\x2', '\x2', '\f', '\x7F', '\x3', 
		'\x2', '\x2', '\x2', '\xE', '\x84', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x12', '\xA0', '\x3', '\x2', '\x2', 
		'\x2', '\x14', '\xA5', '\x3', '\x2', '\x2', '\x2', '\x16', '\x17', '\t', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x3', '\x2', '\x2', '\x2', '\x18', 
		'=', '\x5', '\x2', '\x2', '\x2', '\x19', '\x1D', '\a', '\x3', '\x2', '\x2', 
		'\x1A', '\x1C', '\a', '\xF', '\x2', '\x2', '\x1B', '\x1A', '\x3', '\x2', 
		'\x2', '\x2', '\x1C', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', '\x30', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', ' ', '$', '\x5', '\x2', '\x2', '\x2', '!', '#', '\a', '\xF', 
		'\x2', '\x2', '\"', '!', '\x3', '\x2', '\x2', '\x2', '#', '&', '\x3', 
		'\x2', '\x2', '\x2', '$', '\"', '\x3', '\x2', '\x2', '\x2', '$', '%', 
		'\x3', '\x2', '\x2', '\x2', '%', '\'', '\x3', '\x2', '\x2', '\x2', '&', 
		'$', '\x3', '\x2', '\x2', '\x2', '\'', '+', '\a', '\x4', '\x2', '\x2', 
		'(', '*', '\a', '\xF', '\x2', '\x2', ')', '(', '\x3', '\x2', '\x2', '\x2', 
		'*', '-', '\x3', '\x2', '\x2', '\x2', '+', ')', '\x3', '\x2', '\x2', '\x2', 
		'+', ',', '\x3', '\x2', '\x2', '\x2', ',', '/', '\x3', '\x2', '\x2', '\x2', 
		'-', '+', '\x3', '\x2', '\x2', '\x2', '.', ' ', '\x3', '\x2', '\x2', '\x2', 
		'/', '\x32', '\x3', '\x2', '\x2', '\x2', '\x30', '.', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '\x31', '\x3', '\x2', '\x2', '\x2', '\x31', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x32', '\x30', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\x37', '\x5', '\x2', '\x2', '\x2', '\x34', '\x36', '\a', '\xF', '\x2', 
		'\x2', '\x35', '\x34', '\x3', '\x2', '\x2', '\x2', '\x36', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\x35', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x38', '\x3', '\x2', '\x2', '\x2', '\x38', ':', '\x3', '\x2', '\x2', 
		'\x2', '\x39', '\x37', '\x3', '\x2', '\x2', '\x2', ':', ';', '\a', '\x5', 
		'\x2', '\x2', ';', '=', '\x3', '\x2', '\x2', '\x2', '<', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '<', '\x19', '\x3', '\x2', '\x2', '\x2', '=', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '>', '@', '\a', '\x6', '\x2', '\x2', '?', 
		'>', '\x3', '\x2', '\x2', '\x2', '?', '@', '\x3', '\x2', '\x2', '\x2', 
		'@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\x5', '\x4', 
		'\x3', '\x2', '\x42', '\x43', '\a', '\a', '\x2', '\x2', '\x43', '\x44', 
		'\x5', '\x2', '\x2', '\x2', '\x44', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x45', 'I', '\x5', '\x2', '\x2', '\x2', '\x46', 'H', '\a', '\xF', '\x2', 
		'\x2', 'G', '\x46', '\x3', '\x2', '\x2', '\x2', 'H', 'K', '\x3', '\x2', 
		'\x2', '\x2', 'I', 'G', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\x3', '\x2', 
		'\x2', '\x2', 'J', 'L', '\x3', '\x2', '\x2', '\x2', 'K', 'I', '\x3', '\x2', 
		'\x2', '\x2', 'L', 'P', '\a', '\x4', '\x2', '\x2', 'M', 'O', '\a', '\xF', 
		'\x2', '\x2', 'N', 'M', '\x3', '\x2', '\x2', '\x2', 'O', 'R', '\x3', '\x2', 
		'\x2', '\x2', 'P', 'N', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'T', '\x3', '\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', 
		'\x2', '\x2', 'S', '\x45', '\x3', '\x2', '\x2', '\x2', 'T', 'W', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\x3', 
		'\x2', '\x2', '\x2', 'V', 'Y', '\x3', '\x2', '\x2', '\x2', 'W', 'U', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'Z', '\x5', '\x2', '\x2', '\x2', 'Y', 'X', '\x3', 
		'\x2', '\x2', '\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', '\t', 
		'\x3', '\x2', '\x2', '\x2', '[', '\\', '\a', '\r', '\x2', '\x2', '\\', 
		'`', '\a', '\b', '\x2', '\x2', ']', '_', '\a', '\xF', '\x2', '\x2', '^', 
		']', '\x3', '\x2', '\x2', '\x2', '_', '\x62', '\x3', '\x2', '\x2', '\x2', 
		'`', '^', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x61', '\x63', '\x3', '\x2', '\x2', '\x2', '\x62', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x63', 'g', '\x5', '\b', '\x5', '\x2', '\x64', '\x66', 
		'\a', '\xF', '\x2', '\x2', '\x65', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'\x66', 'i', '\x3', '\x2', '\x2', '\x2', 'g', '\x65', '\x3', '\x2', '\x2', 
		'\x2', 'g', 'h', '\x3', '\x2', '\x2', '\x2', 'h', 'j', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'g', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', '\t', '\x2', 
		'\x2', 'k', '\v', '\x3', '\x2', '\x2', '\x2', 'l', '\x80', '\x5', '\x6', 
		'\x4', '\x2', 'm', '\x80', '\x5', '\x2', '\x2', '\x2', 'n', '\x80', '\x5', 
		'\n', '\x6', '\x2', 'o', 's', '\a', '\b', '\x2', '\x2', 'p', 'r', '\a', 
		'\xF', '\x2', '\x2', 'q', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 'u', '\x3', 
		'\x2', '\x2', '\x2', 's', 'q', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', 
		'\x2', '\x2', '\x2', 't', 'v', '\x3', '\x2', '\x2', '\x2', 'u', 's', '\x3', 
		'\x2', '\x2', '\x2', 'v', 'z', '\x5', '\x14', '\v', '\x2', 'w', 'y', '\a', 
		'\xF', '\x2', '\x2', 'x', 'w', '\x3', '\x2', '\x2', '\x2', 'y', '|', '\x3', 
		'\x2', '\x2', '\x2', 'z', 'x', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\x3', 
		'\x2', '\x2', '\x2', '{', '}', '\x3', '\x2', '\x2', '\x2', '|', 'z', '\x3', 
		'\x2', '\x2', '\x2', '}', '~', '\a', '\t', '\x2', '\x2', '~', '\x80', 
		'\x3', '\x2', '\x2', '\x2', '\x7F', 'l', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		'm', '\x3', '\x2', '\x2', '\x2', '\x7F', 'n', '\x3', '\x2', '\x2', '\x2', 
		'\x7F', 'o', '\x3', '\x2', '\x2', '\x2', '\x80', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x85', '\x5', '\f', '\a', '\x2', '\x82', '\x83', '\a', 
		'\n', '\x2', '\x2', '\x83', '\x85', '\x5', '\f', '\a', '\x2', '\x84', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x84', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\xF', '\x3', '\x2', '\x2', '\x2', '\x86', '\x8A', '\x5', 
		'\xE', '\b', '\x2', '\x87', '\x89', '\a', '\xF', '\x2', '\x2', '\x88', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', '\x8B', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x91', '\a', '\v', '\x2', 
		'\x2', '\x8E', '\x90', '\a', '\xF', '\x2', '\x2', '\x8F', '\x8E', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x93', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\x92', '\x95', '\x3', '\x2', '\x2', '\x2', '\x93', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x94', '\x86', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x96', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x97', '\x3', '\x2', '\x2', '\x2', '\x97', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\x98', '\x96', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x9A', '\x5', '\xE', '\b', '\x2', '\x9A', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x9B', '\x9C', '\x5', '\x10', '\t', '\x2', '\x9C', '\x9D', '\a', 
		'\xF', '\x2', '\x2', '\x9D', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\x9E', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x5', '\x10', '\t', 
		'\x2', '\xA4', '\x13', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\x5', 
		'\x12', '\n', '\x2', '\xA6', '\x15', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'\x1D', '$', '+', '\x30', '\x37', '<', '?', 'I', 'P', 'U', 'Y', '`', 'g', 
		's', 'z', '\x7F', '\x84', '\x8A', '\x91', '\x96', '\xA0',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
