//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SearchGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SearchGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ISearchGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] SearchGrammarParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] SearchGrammarParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.keylist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeylist([NotNull] SearchGrammarParser.KeylistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.keylist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeylist([NotNull] SearchGrammarParser.KeylistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.kvsearch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKvsearch([NotNull] SearchGrammarParser.KvsearchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.kvsearch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKvsearch([NotNull] SearchGrammarParser.KvsearchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] SearchGrammarParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] SearchGrammarParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] SearchGrammarParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] SearchGrammarParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegation([NotNull] SearchGrammarParser.NegationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegation([NotNull] SearchGrammarParser.NegationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr([NotNull] SearchGrammarParser.OrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr([NotNull] SearchGrammarParser.OrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd([NotNull] SearchGrammarParser.AndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd([NotNull] SearchGrammarParser.AndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] SearchGrammarParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] SearchGrammarParser.QueryContext context);
}
