//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SearchGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISearchGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class SearchGrammarBaseListener : ISearchGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] SearchGrammarParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] SearchGrammarParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.keylist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeylist([NotNull] SearchGrammarParser.KeylistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.keylist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeylist([NotNull] SearchGrammarParser.KeylistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.kvsearch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKvsearch([NotNull] SearchGrammarParser.KvsearchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.kvsearch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKvsearch([NotNull] SearchGrammarParser.KvsearchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([NotNull] SearchGrammarParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([NotNull] SearchGrammarParser.ArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] SearchGrammarParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] SearchGrammarParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] SearchGrammarParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] SearchGrammarParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegation([NotNull] SearchGrammarParser.NegationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegation([NotNull] SearchGrammarParser.NegationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr([NotNull] SearchGrammarParser.OrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr([NotNull] SearchGrammarParser.OrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd([NotNull] SearchGrammarParser.AndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd([NotNull] SearchGrammarParser.AndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchGrammarParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuery([NotNull] SearchGrammarParser.QueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchGrammarParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuery([NotNull] SearchGrammarParser.QueryContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
