//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SearchGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SearchGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ISearchGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] SearchGrammarParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.keylist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeylist([NotNull] SearchGrammarParser.KeylistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.valuesearch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValuesearch([NotNull] SearchGrammarParser.ValuesearchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.kvsearch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKvsearch([NotNull] SearchGrammarParser.KvsearchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] SearchGrammarParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] SearchGrammarParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] SearchGrammarParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegation([NotNull] SearchGrammarParser.NegationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr([NotNull] SearchGrammarParser.OrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd([NotNull] SearchGrammarParser.AndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SearchGrammarParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery([NotNull] SearchGrammarParser.QueryContext context);
}
