//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DashSearchGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DashSearchGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IDashSearchGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] DashSearchGrammarParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] DashSearchGrammarParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.function_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_expr([NotNull] DashSearchGrammarParser.Function_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.and_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_token([NotNull] DashSearchGrammarParser.And_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.or_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr_token([NotNull] DashSearchGrammarParser.Or_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator([NotNull] DashSearchGrammarParser.OperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.phrase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhrase([NotNull] DashSearchGrammarParser.PhraseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.kv_search"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKv_search([NotNull] DashSearchGrammarParser.Kv_searchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.search_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSearch_term([NotNull] DashSearchGrammarParser.Search_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.not_search_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot_search_term([NotNull] DashSearchGrammarParser.Not_search_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DashSearchGrammarParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery([NotNull] DashSearchGrammarParser.QueryContext context);
}
