//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DashSearchGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DashSearchGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IDashSearchGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DashSearchGrammarParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] DashSearchGrammarParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DashSearchGrammarParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] DashSearchGrammarParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DashSearchGrammarParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput([NotNull] DashSearchGrammarParser.InputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DashSearchGrammarParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput([NotNull] DashSearchGrammarParser.InputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DashSearchGrammarParser.function_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_expr([NotNull] DashSearchGrammarParser.Function_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DashSearchGrammarParser.function_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_expr([NotNull] DashSearchGrammarParser.Function_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DashSearchGrammarParser.and_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_token([NotNull] DashSearchGrammarParser.And_tokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DashSearchGrammarParser.and_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_token([NotNull] DashSearchGrammarParser.And_tokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DashSearchGrammarParser.or_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr_token([NotNull] DashSearchGrammarParser.Or_tokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DashSearchGrammarParser.or_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr_token([NotNull] DashSearchGrammarParser.Or_tokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DashSearchGrammarParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator([NotNull] DashSearchGrammarParser.OperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DashSearchGrammarParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator([NotNull] DashSearchGrammarParser.OperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DashSearchGrammarParser.phrase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPhrase([NotNull] DashSearchGrammarParser.PhraseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DashSearchGrammarParser.phrase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPhrase([NotNull] DashSearchGrammarParser.PhraseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DashSearchGrammarParser.chain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChain([NotNull] DashSearchGrammarParser.ChainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DashSearchGrammarParser.chain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChain([NotNull] DashSearchGrammarParser.ChainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DashSearchGrammarParser.logical_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_expr([NotNull] DashSearchGrammarParser.Logical_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DashSearchGrammarParser.logical_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_expr([NotNull] DashSearchGrammarParser.Logical_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DashSearchGrammarParser.kv_search"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKv_search([NotNull] DashSearchGrammarParser.Kv_searchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DashSearchGrammarParser.kv_search"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKv_search([NotNull] DashSearchGrammarParser.Kv_searchContext context);
}
