//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\GFX Lab\Desktop\Hannah\Dash\Util\Parser\DashSearchGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class DashSearchGrammarParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, WORD=8, ALPHANUM=9, 
		WHITESPACE=10;
	public const int
		RULE_and_token = 0, RULE_or_token = 1, RULE_operator = 2, RULE_phrase = 3, 
		RULE_chain = 4, RULE_logical_expr = 5, RULE_name = 6, RULE_arguments = 7, 
		RULE_input = 8, RULE_function_expr = 9, RULE_kv_search = 10;
	public static readonly string[] ruleNames = {
		"and_token", "or_token", "operator", "phrase", "chain", "logical_expr", 
		"name", "arguments", "input", "function_expr", "kv_search"
	};

	private static readonly string[] _LiteralNames = {
		null, "'|'", "'\"'", "'!'", "'('", "')'", "','", "':'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, "WORD", "ALPHANUM", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DashSearchGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static DashSearchGrammarParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public DashSearchGrammarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public DashSearchGrammarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class And_tokenContext : ParserRuleContext {
		public ITerminalNode WHITESPACE() { return GetToken(DashSearchGrammarParser.WHITESPACE, 0); }
		public And_tokenContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_and_token; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterAnd_token(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitAnd_token(this);
		}
	}

	[RuleVersion(0)]
	public And_tokenContext and_token() {
		And_tokenContext _localctx = new And_tokenContext(Context, State);
		EnterRule(_localctx, 0, RULE_and_token);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 22; Match(WHITESPACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Or_tokenContext : ParserRuleContext {
		public ITerminalNode[] WHITESPACE() { return GetTokens(DashSearchGrammarParser.WHITESPACE); }
		public ITerminalNode WHITESPACE(int i) {
			return GetToken(DashSearchGrammarParser.WHITESPACE, i);
		}
		public Or_tokenContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_or_token; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterOr_token(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitOr_token(this);
		}
	}

	[RuleVersion(0)]
	public Or_tokenContext or_token() {
		Or_tokenContext _localctx = new Or_tokenContext(Context, State);
		EnterRule(_localctx, 2, RULE_or_token);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 25;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==WHITESPACE) {
				{
				State = 24; Match(WHITESPACE);
				}
			}

			State = 27; Match(T__0);
			State = 29;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==WHITESPACE) {
				{
				State = 28; Match(WHITESPACE);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperatorContext : ParserRuleContext {
		public And_tokenContext and_token() {
			return GetRuleContext<And_tokenContext>(0);
		}
		public Or_tokenContext or_token() {
			return GetRuleContext<Or_tokenContext>(0);
		}
		public OperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operator; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterOperator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitOperator(this);
		}
	}

	[RuleVersion(0)]
	public OperatorContext @operator() {
		OperatorContext _localctx = new OperatorContext(Context, State);
		EnterRule(_localctx, 4, RULE_operator);
		try {
			State = 33;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 31; and_token();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 32; or_token();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PhraseContext : ParserRuleContext {
		public ITerminalNode ALPHANUM() { return GetToken(DashSearchGrammarParser.ALPHANUM, 0); }
		public PhraseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_phrase; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterPhrase(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitPhrase(this);
		}
	}

	[RuleVersion(0)]
	public PhraseContext phrase() {
		PhraseContext _localctx = new PhraseContext(Context, State);
		EnterRule(_localctx, 6, RULE_phrase);
		try {
			int _alt;
			State = 44;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ALPHANUM:
				EnterOuterAlt(_localctx, 1);
				{
				State = 35; Match(ALPHANUM);
				}
				break;
			case T__1:
				EnterOuterAlt(_localctx, 2);
				{
				State = 36; Match(T__1);
				State = 40;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
				while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1+1 ) {
						{
						{
						State = 37;
						MatchWildcard();
						}
						} 
					}
					State = 42;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
				}
				State = 43; Match(T__1);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ChainContext : ParserRuleContext {
		public PhraseContext[] phrase() {
			return GetRuleContexts<PhraseContext>();
		}
		public PhraseContext phrase(int i) {
			return GetRuleContext<PhraseContext>(i);
		}
		public OperatorContext[] @operator() {
			return GetRuleContexts<OperatorContext>();
		}
		public OperatorContext @operator(int i) {
			return GetRuleContext<OperatorContext>(i);
		}
		public ChainContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_chain; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterChain(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitChain(this);
		}
	}

	[RuleVersion(0)]
	public ChainContext chain() {
		ChainContext _localctx = new ChainContext(Context, State);
		EnterRule(_localctx, 8, RULE_chain);
		int _la;
		try {
			int _alt;
			State = 59;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 47;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__2) {
					{
					State = 46; Match(T__2);
					}
				}

				State = 49; phrase();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 53;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 50; phrase();
						State = 51; @operator();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 55;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 57; phrase();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Logical_exprContext : ParserRuleContext {
		public ChainContext chain() {
			return GetRuleContext<ChainContext>(0);
		}
		public Logical_exprContext[] logical_expr() {
			return GetRuleContexts<Logical_exprContext>();
		}
		public Logical_exprContext logical_expr(int i) {
			return GetRuleContext<Logical_exprContext>(i);
		}
		public OperatorContext @operator() {
			return GetRuleContext<OperatorContext>(0);
		}
		public Logical_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logical_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterLogical_expr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitLogical_expr(this);
		}
	}

	[RuleVersion(0)]
	public Logical_exprContext logical_expr() {
		return logical_expr(0);
	}

	private Logical_exprContext logical_expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		Logical_exprContext _localctx = new Logical_exprContext(Context, _parentState);
		Logical_exprContext _prevctx = _localctx;
		int _startState = 10;
		EnterRecursionRule(_localctx, 10, RULE_logical_expr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 67;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__1:
			case T__2:
			case ALPHANUM:
				{
				State = 62; chain();
				}
				break;
			case T__3:
				{
				State = 63; Match(T__3);
				State = 64; logical_expr(0);
				State = 65; Match(T__4);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 75;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new Logical_exprContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_logical_expr);
					State = 69;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 70; @operator();
					State = 71; logical_expr(3);
					}
					} 
				}
				State = 77;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class NameContext : ParserRuleContext {
		public ITerminalNode WORD() { return GetToken(DashSearchGrammarParser.WORD, 0); }
		public NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitName(this);
		}
	}

	[RuleVersion(0)]
	public NameContext name() {
		NameContext _localctx = new NameContext(Context, State);
		EnterRule(_localctx, 12, RULE_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78; Match(WORD);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentsContext : ParserRuleContext {
		public ITerminalNode[] ALPHANUM() { return GetTokens(DashSearchGrammarParser.ALPHANUM); }
		public ITerminalNode ALPHANUM(int i) {
			return GetToken(DashSearchGrammarParser.ALPHANUM, i);
		}
		public ArgumentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arguments; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterArguments(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitArguments(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentsContext arguments() {
		ArgumentsContext _localctx = new ArgumentsContext(Context, State);
		EnterRule(_localctx, 14, RULE_arguments);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 82;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 80; Match(ALPHANUM);
					State = 81; Match(T__5);
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 84;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			State = 86; Match(ALPHANUM);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InputContext : ParserRuleContext {
		public ArgumentsContext arguments() {
			return GetRuleContext<ArgumentsContext>(0);
		}
		public InputContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_input; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterInput(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitInput(this);
		}
	}

	[RuleVersion(0)]
	public InputContext input() {
		InputContext _localctx = new InputContext(Context, State);
		EnterRule(_localctx, 16, RULE_input);
		try {
			State = 90;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__4:
				EnterOuterAlt(_localctx, 1);
				{
				}
				break;
			case ALPHANUM:
				EnterOuterAlt(_localctx, 2);
				{
				State = 89; arguments();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_exprContext : ParserRuleContext {
		public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		public InputContext input() {
			return GetRuleContext<InputContext>(0);
		}
		public Function_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterFunction_expr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitFunction_expr(this);
		}
	}

	[RuleVersion(0)]
	public Function_exprContext function_expr() {
		Function_exprContext _localctx = new Function_exprContext(Context, State);
		EnterRule(_localctx, 18, RULE_function_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92; name();
			State = 93; Match(T__3);
			State = 94; input();
			State = 95; Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Kv_searchContext : ParserRuleContext {
		public PhraseContext[] phrase() {
			return GetRuleContexts<PhraseContext>();
		}
		public PhraseContext phrase(int i) {
			return GetRuleContext<PhraseContext>(i);
		}
		public Kv_searchContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_kv_search; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.EnterKv_search(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDashSearchGrammarListener typedListener = listener as IDashSearchGrammarListener;
			if (typedListener != null) typedListener.ExitKv_search(this);
		}
	}

	[RuleVersion(0)]
	public Kv_searchContext kv_search() {
		Kv_searchContext _localctx = new Kv_searchContext(Context, State);
		EnterRule(_localctx, 20, RULE_kv_search);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97; phrase();
			State = 98; Match(T__6);
			State = 99; phrase();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 5: return logical_expr_sempred((Logical_exprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool logical_expr_sempred(Logical_exprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\f', 'h', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', '\t', 
		'\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', '\x6', 
		'\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', '\x4', 
		'\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', '\x4', 
		'\f', '\t', '\f', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x5', '\x3', 
		'\x1C', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', ' ', '\n', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '$', '\n', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', ')', '\n', '\x5', '\f', 
		'\x5', '\xE', '\x5', ',', '\v', '\x5', '\x3', '\x5', '\x5', '\x5', '/', 
		'\n', '\x5', '\x3', '\x6', '\x5', '\x6', '\x32', '\n', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x6', '\x6', '\x38', '\n', 
		'\x6', '\r', '\x6', '\xE', '\x6', '\x39', '\x3', '\x6', '\x3', '\x6', 
		'\x5', '\x6', '>', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', '\x46', '\n', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\a', '\a', 'L', '\n', 
		'\a', '\f', '\a', '\xE', '\a', 'O', '\v', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x6', '\t', 'U', '\n', '\t', '\r', '\t', '\xE', 
		'\t', 'V', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x5', 
		'\n', ']', '\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '*', '\x3', '\f', '\r', '\x2', '\x4', '\x6', '\b', '\n', 
		'\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x2', '\x2', '\x2', 'h', 
		'\x2', '\x18', '\x3', '\x2', '\x2', '\x2', '\x4', '\x1B', '\x3', '\x2', 
		'\x2', '\x2', '\x6', '#', '\x3', '\x2', '\x2', '\x2', '\b', '.', '\x3', 
		'\x2', '\x2', '\x2', '\n', '=', '\x3', '\x2', '\x2', '\x2', '\f', '\x45', 
		'\x3', '\x2', '\x2', '\x2', '\xE', 'P', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'T', '\x3', '\x2', '\x2', '\x2', '\x12', '\\', '\x3', '\x2', '\x2', '\x2', 
		'\x14', '^', '\x3', '\x2', '\x2', '\x2', '\x16', '\x63', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '\x19', '\a', '\f', '\x2', '\x2', '\x19', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x1A', '\x1C', '\a', '\f', '\x2', '\x2', 
		'\x1B', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', '\x1C', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x1F', 
		'\a', '\x3', '\x2', '\x2', '\x1E', ' ', '\a', '\f', '\x2', '\x2', '\x1F', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x1F', ' ', '\x3', '\x2', '\x2', 
		'\x2', ' ', '\x5', '\x3', '\x2', '\x2', '\x2', '!', '$', '\x5', '\x2', 
		'\x2', '\x2', '\"', '$', '\x5', '\x4', '\x3', '\x2', '#', '!', '\x3', 
		'\x2', '\x2', '\x2', '#', '\"', '\x3', '\x2', '\x2', '\x2', '$', '\a', 
		'\x3', '\x2', '\x2', '\x2', '%', '/', '\a', '\v', '\x2', '\x2', '&', '*', 
		'\a', '\x4', '\x2', '\x2', '\'', ')', '\v', '\x2', '\x2', '\x2', '(', 
		'\'', '\x3', '\x2', '\x2', '\x2', ')', ',', '\x3', '\x2', '\x2', '\x2', 
		'*', '+', '\x3', '\x2', '\x2', '\x2', '*', '(', '\x3', '\x2', '\x2', '\x2', 
		'+', '-', '\x3', '\x2', '\x2', '\x2', ',', '*', '\x3', '\x2', '\x2', '\x2', 
		'-', '/', '\a', '\x4', '\x2', '\x2', '.', '%', '\x3', '\x2', '\x2', '\x2', 
		'.', '&', '\x3', '\x2', '\x2', '\x2', '/', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '\x32', '\a', '\x5', '\x2', '\x2', '\x31', '\x30', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x32', '\x3', '\x2', '\x2', '\x2', '\x32', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x33', '>', '\x5', '\b', '\x5', '\x2', 
		'\x34', '\x35', '\x5', '\b', '\x5', '\x2', '\x35', '\x36', '\x5', '\x6', 
		'\x4', '\x2', '\x36', '\x38', '\x3', '\x2', '\x2', '\x2', '\x37', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\x38', '\x39', '\x3', '\x2', '\x2', '\x2', 
		'\x39', '\x37', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\x3', '\x2', 
		'\x2', '\x2', ':', ';', '\x3', '\x2', '\x2', '\x2', ';', '<', '\x5', '\b', 
		'\x5', '\x2', '<', '>', '\x3', '\x2', '\x2', '\x2', '=', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '=', '\x37', '\x3', '\x2', '\x2', '\x2', '>', '\v', 
		'\x3', '\x2', '\x2', '\x2', '?', '@', '\b', '\a', '\x1', '\x2', '@', '\x46', 
		'\x5', '\n', '\x6', '\x2', '\x41', '\x42', '\a', '\x6', '\x2', '\x2', 
		'\x42', '\x43', '\x5', '\f', '\a', '\x2', '\x43', '\x44', '\a', '\a', 
		'\x2', '\x2', '\x44', '\x46', '\x3', '\x2', '\x2', '\x2', '\x45', '?', 
		'\x3', '\x2', '\x2', '\x2', '\x45', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\x46', 'M', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\f', '\x4', '\x2', 
		'\x2', 'H', 'I', '\x5', '\x6', '\x4', '\x2', 'I', 'J', '\x5', '\f', '\a', 
		'\x5', 'J', 'L', '\x3', '\x2', '\x2', '\x2', 'K', 'G', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'O', '\x3', '\x2', '\x2', '\x2', 'M', 'K', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'N', '\x3', '\x2', '\x2', '\x2', 'N', '\r', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'M', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\a', '\n', 
		'\x2', '\x2', 'Q', '\xF', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\a', 
		'\v', '\x2', '\x2', 'S', 'U', '\a', '\b', '\x2', '\x2', 'T', 'R', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'V', '\x3', '\x2', '\x2', '\x2', 'V', 'T', '\x3', 
		'\x2', '\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'Y', '\a', '\v', '\x2', '\x2', 'Y', '\x11', 
		'\x3', '\x2', '\x2', '\x2', 'Z', ']', '\x3', '\x2', '\x2', '\x2', '[', 
		']', '\x5', '\x10', '\t', '\x2', '\\', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'\\', '[', '\x3', '\x2', '\x2', '\x2', ']', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '^', '_', '\x5', '\xE', '\b', '\x2', '_', '`', '\a', '\x6', '\x2', 
		'\x2', '`', '\x61', '\x5', '\x12', '\n', '\x2', '\x61', '\x62', '\a', 
		'\a', '\x2', '\x2', '\x62', '\x15', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\x64', '\x5', '\b', '\x5', '\x2', '\x64', '\x65', '\a', '\t', '\x2', 
		'\x2', '\x65', '\x66', '\x5', '\b', '\x5', '\x2', '\x66', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\xE', '\x1B', '\x1F', '#', '*', '.', '\x31', '\x39', 
		'=', '\x45', 'M', 'V', '\\',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
